// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendorMngSystem.DbData;

#nullable disable

namespace VendorMngSystem.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20261005172640_UpdateVendorStatus")]
    partial class UpdateVendorStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VendorMngSystem.Models.Vendors", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VendorStatus")
                        .HasColumnType("bit");

                    b.Property<int>("VendorsCategoryId")
                        .HasColumnType("int");

                    b.HasKey("VendorId");

                    b.HasIndex("VendorsCategoryId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("VendorMngSystem.Models.VendorsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("VendorsCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VendorsCategories");
                });

            modelBuilder.Entity("VendorMngSystem.Models.Vendors", b =>
                {
                    b.HasOne("VendorMngSystem.Models.VendorsCategory", "vendorsCategories")
                        .WithMany("vendors")
                        .HasForeignKey("VendorsCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("vendorsCategories");
                });

            modelBuilder.Entity("VendorMngSystem.Models.VendorsCategory", b =>
                {
                    b.Navigation("vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
